server:
  port: 9000

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
    database: 2
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

token:
  header: Authorization # 令牌自定义标识
  secret: abcdefghijklmnopqrstuvwxyz # 令牌密钥
  expireTime: 4320 # 令牌有效期（默认3天）

mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.roydon.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
