# 项目相关配置
community:
  name: community # 名称
  version: 1.0.0
  copyrightYear: 2022
  demoEnabled: true # 实例演示开关
  profile: /root/community/uploadPath # 文件路径 （ Windows配置D:/community/uploadPath，Linux配置 /root/community/uploadPath）
  addressEnabled: true # 获取ip地址开关
  captchaType: char # 验证码类型 math 数组计算 char 字符验证

spring:
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件大小
      max-request-size: 20MB # 设置总上传的文件大小
  datasource:
    druid:
      master:
        host: 106.14.105.101:3306
        database: community-server
        username: roydon
        password: roydon#Mysql
  redis:
    host: 8.132.211.245 # r-uf673npd2sfuujqlaipd.redis.rds.aliyuncs.com
    port: 6379
    password: roydon#Redis
    database: 0
  rabbitmq:
    host: 106.14.105.101
    port: 5672
    username: roydon
    password: qwer1234
    virtual-host: /

token:
  header: Authorization # 令牌自定义标识
  secret: abcdefghijklmnopqrstuvwxyz # 令牌密钥
  expireTime: 1440 # 令牌有效期（默认1天）（单位：分钟）

user:
  password:
    maxRetryCount: 5 # 密码最大错误次数
    lockTime: 1 # 密码锁定时间（默认1分钟）

aliyun: # aliyun配置
  sms:
    templateCode: SMS_460955023 # 可在aliyun控制台申请
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucketname: community-server-oss

openai: # openai密钥
  gpt:
    model: text-davinci-003 #达芬奇模型
    token: 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
    timeout: 100000 #超时时间
