

server:
  port: 8088
  servlet:
    context-path: / # 应用的访问路径
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000 # 连接数满后的排队数，默认为100
    threads:
      max: 800 # tomcat最大线程数，默认为200
      min-spare: 100 # Tomcat启动初始化的线程数，默认值10

# Spring配置
spring:
  messages:
    basename: i18n/messages # 国际化资源文件路径
    encoding: UTF-8
  profiles:
    active: pro
  servlet:
    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size} # 单个文件大小
      max-request-size: ${spring.servlet.multipart.max-request-size} # 设置总上传的文件大小
  devtools:
    restart:
      enabled: true # 热部署开关
  datasource: # 数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      master: # 主库数据源
        url: jdbc:mysql://${spring.datasource.druid.master.host}/${spring.datasource.druid.master.database}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: ${spring.datasource.druid.master.username}
        password: ${spring.datasource.druid.master.password}
      slave: # 从库数据源
        enabled: false # 从数据源开关/默认关闭
        url:
        username:
        password:
      # 初始连接数
      initialSize: 10
      # 最小连接池数量
      minIdle: 20
      # 最大连接池数量
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ${spring.datasource.druid.master.username}
        login-password: ${spring.datasource.druid.master.password}
      filter:
        stat:
          enabled: true
          log-slow-sql: true # 慢SQL记录
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    password: ${spring.redis.password}
    database: ${spring.redis.database}
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-active: 8 # 连接池的最大数据库连接数
        max-wait: -1ms # #连接池最大阻塞等待时间（使用负值表示没有限制）
  rabbitmq:
    host: ${spring.rabbitmq.host}
    port: ${spring.rabbitmq.port}
    username: ${spring.rabbitmq.username}
    password: ${spring.rabbitmq.password}
    virtual-host: ${spring.rabbitmq.virtual-host}

logging:
  level:
    com.roydon: debug
    org.springframework: warn

# 用户配置
#user:
#  password:
#    maxRetryCount: 5 # 密码最大错误次数
#    lockTime: 1 # 密码锁定时间（默认1分钟）

# token配置
#token:
#  header: Authorization # 令牌自定义标识
#  secret: abcdefghijklmnopqrstuvwxyz # 令牌密钥
#  expireTime: 1440 # 令牌有效期（默认1天）（单位：分钟）

mybatis-plus:
  type-aliases-package: com.roydon.**.domain # 搜索指定包别名
  mapper-locations: classpath*:mapper/**/*Mapper.xml # 配置mapper的扫描，找到所有的mapper.xml映射文件
  config-location: classpath:mybatis/mybatis-config.xml # 加载全局的配置文件
#  global-config:
#    db-config:
#      id-type: auto # 设置id自增

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

swagger:
  enabled: true
  pathMapping: /dev-api # 请求前缀

# 防止XSS攻击
xss:
  enabled: true
  excludes: /system/notice # 排除链接（多个用逗号分隔）
  urlPatterns: /system/*,/monitor/*,/tool/* # 匹配链接

